# Quarto extensions used: 
# - https://github.com/schochastics/academicons
# - https://github.com/quarto-ext/fontawesome

# TODO: 
# - Jobs
# - References
# Bessere Buttons
# Hintergründe als angedeutete Diagramme

project:
  type: website
  output-dir: docs

execute:
  cache: false

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  
  navbar:
    title: false
    search: false
    logo: "img/BioMath_logo_name_weiss_1500x399.png"
    right:
      - text: Services
        href: services.qmd
      - text: Methods
        href: methods.qmd
      - text: References
        href: references.qmd


  page-footer:
    left: |
      BioMath GmbH<br>
      Eppendorfer Weg 255, 20251 Hamburg, Germany
    center: |
      [Legal Notice](legal_notice.qmd) | [Privacy Policy](privacy_policy.qmd)
    right: |
      central@biomath.de<br>
      Managing directors: Dr. Kerstin Schmidt, [Dr. Paul Schmidt](https://schmidtpaul.github.io/)
    border: false
    background: $bm-green

      
format:
  html:
    theme: [cosmo, styles.scss]
    anchor-sections: false

